version: "3.9"
services:
#  webapp:
#    container_name: "webapp"
#    image: "seikodocker/webapp:v0.2"
#    ports:
#      - "8081:8081"
#    depends_on:
#      - redis
#    expose:
#      - 8081

  redis:
    image: "redis"
    container_name: "redis-server"
    ports:
      - "6379:6379"
    expose:
      - "6379"
    restart: always

  mysql:
    image: "mysql"
    container_name: "mysql"
    volumes:
      - "/home/seiko/mysql/data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    expose:
      - "3306"
    restart: always