server:
  port: 0
  servlet:
    context-path: /client
    session:
      timeout: 30s
      cookie:
        max-age: 30s

management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  redis:
    host: localhost
    port: 6379
    password: ''
    timeout: 1m
  session:
    store-type: redis
    timeout: 1m

  security:
    oauth2:
      client:
        registration:
          citi:
            client-id: Client
            client-secret: 123
            redirect-uri: http://localhost:8081/client/index
            authorization-grant-type: authorization_code
          google:
            client-id: Client
            client-secret: 123
            redirect-uri: http://localhost:8081/client/index
            authorization-grant-type: authorization_code
        provider:
          citi:
            authorization-uri: http://localhost:8082/auth-server/oauth/authorize
            token-uri: http://localhost:8082/auth-server/oauth/token
            user-info-uri: http://localhost:8082/auth-server/me
          google:
            authorization-uri: http://localhost:8082/auth-server/oauth/authorize
            token-uri: http://localhost:8082/auth-server/oauth/token
            user-info-uri: http://localhost:8082/auth-server/me


